/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AK STUDIO (https://sketchfab.com/inven2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-992750b0df674378989fa915b0688ce1
Title: Coffee Cup
*/

import { createExternalResource } from '@/utils/resourceUtils';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		defaultMaterial: THREE.Mesh;
	};
	materials: {
		DefaultMaterial: THREE.MeshStandardMaterial;
	};
};

const localPath = 'models/coffee_cup.glb';
const uploadThingId = 'ayWUAmbcwFZQJTwmTIg7EvFUGfmSCukPROQ0aZYiJcAqLgeT';
const externalResource = createExternalResource(localPath, uploadThingId);

export function CoffeeMug(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF(externalResource) as GLTFResult;

	return (
		<group {...props} dispose={null} scale={0.8}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.0992}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.defaultMaterial.geometry}
					material={materials.DefaultMaterial}
					rotation={[Math.PI / 2, 0, 0]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload(externalResource);
