/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RMrando (https://sketchfab.com/RMrando)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mouse-and-keyboard-d91b625d38a64ed39c1dfaef28e588d7
Title: Mouse and Keyboard
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		Cube048_Mouse_0: THREE.Mesh;
		Keycap033_Mouse_0: THREE.Mesh;
		KeycapOG127_Mouse_0: THREE.Mesh;
		SPACE010_Mouse_0: THREE.Mesh;
		KeycapOG128_Mouse_0: THREE.Mesh;
		KeycapOG129_Mouse_0: THREE.Mesh;
		KeycapOG130_Mouse_0: THREE.Mesh;
		KeycapOG131_Mouse_0: THREE.Mesh;
		KeycapOG132_Mouse_0: THREE.Mesh;
		KeycapOG133_Mouse_0: THREE.Mesh;
		KeycapOG134_Mouse_0: THREE.Mesh;
		KeycapOG135_Mouse_0: THREE.Mesh;
		KeycapOG136_Mouse_0: THREE.Mesh;
		KeycapOG137_Mouse_0: THREE.Mesh;
		KeycapOG138_Mouse_0: THREE.Mesh;
		KeycapOG139_Mouse_0: THREE.Mesh;
		KeycapOG140_Mouse_0: THREE.Mesh;
		Keycap034_Mouse_0: THREE.Mesh;
		Keycap035_Mouse_0: THREE.Mesh;
		Keycap036_Mouse_0: THREE.Mesh;
		Mouse_body_low005_Mouse_0: THREE.Mesh;
		Mouse_Click_low005_Mouse_0: THREE.Mesh;
		Mouse_side_low005_Mouse_0: THREE.Mesh;
		Mouse_wheel_low005_Mouse_0: THREE.Mesh;
		Mouse_bottom_flat_low005_Mouse_0: THREE.Mesh;
	};
	materials: {
		Mouse: THREE.MeshStandardMaterial;
	};
};

export function KeyboardAndMouse(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('/models/mouse_and_keyboard.glb') as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group scale={0.01}>
				<group
					position={[-0.0601, 0.7954, -0.0338]}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube048_Mouse_0.geometry}
						material={materials.Mouse}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Keycap033_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.0877, -0.0184, 0.0096]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG127_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.1246, 0.0183, 0.0118]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.SPACE010_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.0118, -0.0373, 0.0085]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG128_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.1227, -0.0001, 0.0107]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG129_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.1182, -0.0185, 0.0096]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG130_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.1271, -0.037, 0.0085]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG131_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.1038, -0.037, 0.0085]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG132_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.0807, -0.037, 0.0085]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG133_Mouse_0.geometry}
						material={materials.Mouse}
						position={[0.0579, -0.037, 0.0085]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG134_Mouse_0.geometry}
						material={materials.Mouse}
						position={[0.0807, -0.037, 0.0085]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG135_Mouse_0.geometry}
						material={materials.Mouse}
						position={[0.1037, -0.037, 0.0085]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG136_Mouse_0.geometry}
						material={materials.Mouse}
						position={[0.1268, -0.037, 0.0085]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG137_Mouse_0.geometry}
						material={materials.Mouse}
						position={[0.1134, -0.0186, 0.0096]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG138_Mouse_0.geometry}
						material={materials.Mouse}
						position={[0.1159, -0.0004, 0.0107]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG139_Mouse_0.geometry}
						material={materials.Mouse}
						position={[0.1239, 0.018, 0.0118]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeycapOG140_Mouse_0.geometry}
						material={materials.Mouse}
						position={[0.1191, 0.0367, 0.0129]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Keycap034_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.0971, -0.0002, 0.0107]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Keycap035_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.1012, 0.0182, 0.0118]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Keycap036_Mouse_0.geometry}
						material={materials.Mouse}
						position={[-0.1293, 0.0368, 0.0129]}
					/>
				</group>
				<group position={[8, 0, 6]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Mouse_body_low005_Mouse_0.geometry}
						material={materials.Mouse}
						position={[19.9015, 2.1491, 0.1431]}
						rotation={[-Math.PI / 2, 0, -1.5649]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Mouse_Click_low005_Mouse_0.geometry}
						material={materials.Mouse}
						position={[19.9015, 2.1491, 0.1431]}
						rotation={[-Math.PI / 2, 0, -1.5649]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Mouse_side_low005_Mouse_0.geometry}
						material={materials.Mouse}
						position={[19.9015, 2.1491, 0.1431]}
						rotation={[-Math.PI / 2, 0, -1.5649]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Mouse_wheel_low005_Mouse_0.geometry}
						material={materials.Mouse}
						position={[19.8625, 2.2991, -3.3285]}
						rotation={[-Math.PI / 2, 0, -1.5649]}
						scale={100}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Mouse_bottom_flat_low005_Mouse_0.geometry}
						material={materials.Mouse}
						position={[19.9015, 2.1491, 0.1431]}
						rotation={[-Math.PI / 2, 0, -1.5649]}
						scale={100}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/models/mouse_and_keyboard.glb');
