/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExperimentsRoomImport } from './routes/experiments/room'
import { Route as ExperimentsBoxesImport } from './routes/experiments/boxes'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExperimentsRoomRoute = ExperimentsRoomImport.update({
  id: '/experiments/room',
  path: '/experiments/room',
  getParentRoute: () => rootRoute,
} as any)

const ExperimentsBoxesRoute = ExperimentsBoxesImport.update({
  id: '/experiments/boxes',
  path: '/experiments/boxes',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/experiments/boxes': {
      id: '/experiments/boxes'
      path: '/experiments/boxes'
      fullPath: '/experiments/boxes'
      preLoaderRoute: typeof ExperimentsBoxesImport
      parentRoute: typeof rootRoute
    }
    '/experiments/room': {
      id: '/experiments/room'
      path: '/experiments/room'
      fullPath: '/experiments/room'
      preLoaderRoute: typeof ExperimentsRoomImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiments/boxes': typeof ExperimentsBoxesRoute
  '/experiments/room': typeof ExperimentsRoomRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiments/boxes': typeof ExperimentsBoxesRoute
  '/experiments/room': typeof ExperimentsRoomRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/experiments/boxes': typeof ExperimentsBoxesRoute
  '/experiments/room': typeof ExperimentsRoomRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experiments/boxes' | '/experiments/room'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiments/boxes' | '/experiments/room'
  id: '__root__' | '/' | '/experiments/boxes' | '/experiments/room'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperimentsBoxesRoute: typeof ExperimentsBoxesRoute
  ExperimentsRoomRoute: typeof ExperimentsRoomRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperimentsBoxesRoute: ExperimentsBoxesRoute,
  ExperimentsRoomRoute: ExperimentsRoomRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/experiments/boxes",
        "/experiments/room"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/experiments/boxes": {
      "filePath": "experiments/boxes.tsx"
    },
    "/experiments/room": {
      "filePath": "experiments/room.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
