/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExperimentsIndexImport } from './routes/experiments/index'

// Create Virtual Routes

const ExperimentsThreeJsTestLazyImport = createFileRoute(
  '/experiments/three-js-test',
)()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExperimentsIndexRoute = ExperimentsIndexImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => rootRoute,
} as any)

const ExperimentsThreeJsTestLazyRoute = ExperimentsThreeJsTestLazyImport.update(
  {
    id: '/experiments/three-js-test',
    path: '/experiments/three-js-test',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/experiments/three-js-test.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/experiments/three-js-test': {
      id: '/experiments/three-js-test'
      path: '/experiments/three-js-test'
      fullPath: '/experiments/three-js-test'
      preLoaderRoute: typeof ExperimentsThreeJsTestLazyImport
      parentRoute: typeof rootRoute
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiments/three-js-test': typeof ExperimentsThreeJsTestLazyRoute
  '/experiments': typeof ExperimentsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiments/three-js-test': typeof ExperimentsThreeJsTestLazyRoute
  '/experiments': typeof ExperimentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/experiments/three-js-test': typeof ExperimentsThreeJsTestLazyRoute
  '/experiments/': typeof ExperimentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experiments/three-js-test' | '/experiments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiments/three-js-test' | '/experiments'
  id: '__root__' | '/' | '/experiments/three-js-test' | '/experiments/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperimentsThreeJsTestLazyRoute: typeof ExperimentsThreeJsTestLazyRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperimentsThreeJsTestLazyRoute: ExperimentsThreeJsTestLazyRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/experiments/three-js-test",
        "/experiments/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/experiments/three-js-test": {
      "filePath": "experiments/three-js-test.lazy.tsx"
    },
    "/experiments/": {
      "filePath": "experiments/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
